sudo: required

language: python
python:
- '2.7'

services:
- docker

before_install:
- tar xvf deployment_keys.tar

before_script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- eval "$(ssh-agent -s)"
- chmod 600 deployment_keys/deploy_test
- ssh-add deployment_keys/deploy_test
- chmod 600 deployment_keys/deploy_prod
- ssh-add deployment_keys/deploy_prod

script:
- export DOCKER_REPO=potic/potic-ranker
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
- export TAG_VERSION=`cat VERSION`.$TRAVIS_BUILD_NUMBER
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG_VERSION
- docker push $DOCKER_REPO
- if [ "$TRAVIS_BRANCH" == "develop" ]; then ssh -o "StrictHostKeyChecking no" "$DEPLOY_TEST_USER"@"$DEPLOY_TEST_HOST" TAG_TO_DEPLOY=$TAG_VERSION ENVIRONMENT_NAME=test POCKET_APP_KEY=$POCKET_APP_KEY 'bash -s' < scripts/deploy.sh; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then ssh -o "StrictHostKeyChecking no" "$DEPLOY_PROD_USER"@"$DEPLOY_PROD_HOST" TAG_TO_DEPLOY=$TAG_VERSION ENVIRONMENT_NAME=prod POCKET_APP_KEY=$POCKET_APP_KEY 'bash -s' < scripts/deploy.sh; fi
